/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CommunicationplatformMagdaDoc {
        "apiurl": string;
        "columns": string;
    }
}
declare global {
    interface HTMLCommunicationplatformMagdaDocElement extends Components.CommunicationplatformMagdaDoc, HTMLStencilElement {
    }
    var HTMLCommunicationplatformMagdaDocElement: {
        prototype: HTMLCommunicationplatformMagdaDocElement;
        new (): HTMLCommunicationplatformMagdaDocElement;
    };
    interface HTMLElementTagNameMap {
        "communicationplatform-magda-doc": HTMLCommunicationplatformMagdaDocElement;
    }
}
declare namespace LocalJSX {
    interface CommunicationplatformMagdaDoc {
        "apiurl": string;
        "columns"?: string;
    }
    interface IntrinsicElements {
        "communicationplatform-magda-doc": CommunicationplatformMagdaDoc;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "communicationplatform-magda-doc": LocalJSX.CommunicationplatformMagdaDoc & JSXBase.HTMLAttributes<HTMLCommunicationplatformMagdaDocElement>;
        }
    }
}
